version: '3.8'

services:
  trino-test:
    build: .
    container_name: trino-test
    ports:
      - "8081:8080"
    volumes:
      - C:/Users/marco/code/test_superseyt/trino_test/catalog:/etc/trino/catalog
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"